=== JeromeAstero/JD2018-11-13/src/by/it/mnovikov/jd02_07/organization.dtd
<?xml version="1.0" encoding="UTF-8" ?>
        <!ELEMENT organizations (organization)+>
        <!ELEMENT organization (name, adress, telephone, email, ads)>
        <!ATTLIST organization
                login ID #REQUIRED
                password CDATA #REQUIRED
                >
        <!ELEMENT name (#PCDATA)>
        <!ELEMENT adress (#PCDATA)>
        <!ELEMENT telephone (#PCDATA)>
        <!ELEMENT email (#PCDATA)>
        <!ELEMENT ads (ad)*>
        <!ELEMENT ad (title, discription, sampler_type, sampler_title, productivity, price)>
        <!ELEMENT title (#PCDATA)>
        <!ELEMENT discription (#PCDATA)>
        <!ELEMENT sampler_type (#PCDATA)>
        <!ELEMENT sampler_title (#PCDATA)>
        <!ELEMENT productivity (#PCDATA)>
        <!ELEMENT price (#PCDATA)>

=== JeromeAstero/JD2018-11-13/src/by/it/mnovikov/jd02_07/organization+DTD.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE organizations SYSTEM "organization.dtd">
<organizations>
    <organization login = "SQ_0818" password = "$0ilqu@lity0818">
        <name>SoilQuality</name>
        <adress>Минск, Кнорина, 111</adress>
        <telephone>+375-29-288-12-19</telephone>
        <email>soilquality@mail.ru</email>
        <ads>
            <ad>
                <title>Fast soil sampling</title>
                <discription>Проведение пробоотбора проб почвы с использованием средств механизации</discription>
                <sampler_type>автоматический</sampler_type>
                <sampler_title>Nietfeld Speedprobe</sampler_title>
                <productivity>60 проб/час</productivity>
                <price>20 руб./га</price>
            </ad>
            <ad>
                <title>Slow soil sampling</title>
                <discription>Проведение пробоотбора проб почвы без использования средств механизации</discription>
                <sampler_type>ручной</sampler_type>
                <sampler_title>Nietfeld Speedprobe</sampler_title>
                <productivity>10 проб/час</productivity>
                <price>10 руб./га</price>
            </ad>
        </ads>
    </organization>
</organizations>
