=== JeromeAstero/JD2018-11-13/src/by/it/denisova/jd02_07/english.dtd
<?xml version="1.0" encoding="utf-8" ?>

        <!ELEMENT persons (person)+>
        <!ELEMENT person (email,nickname,password,themes)>
        <!ELEMENT email (#PCDATA)>
        <!ELEMENT nickname (#PCDATA)>
        <!ELEMENT password (#PCDATA)>

<!ELEMENT themes (theme)*>
<!ELEMENT theme (name,lessons)*>
<!ELEMENT lessons (lesson)>
<!ELEMENT lesson (name,theory, test)>

     <!ELEMENT name (#PCDATA)>
     <!ELEMENT theory (#PCDATA)>
     <!ELEMENT test (questions)>
         <!ELEMENT questions (question)+>
         <!ELEMENT question (nameQuestion,answers)>
        <!ELEMENT nameQuestion (#PCDATA)>
        <!ELEMENT answers (answer)+>
            <!ELEMENT answer (#PCDATA)>

=== JeromeAstero/JD2018-11-13/src/by/it/denisova/jd02_07/english+dtd.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE persons SYSTEM "english.dtd">
<persons>
    <person>
        <email>katia@mail.ru</email>
        <nickname>k_den11</nickname>
        <password>qwerty12345</password>
        <themes>
            <theme>
                <name>Animals</name>
                <lessons>
                    <lesson>
                        <name>Animals read</name>
                        <theory> some theory(lions live 10 years)</theory>
                        <test>
                            <questions>
                                <question>
                                    <nameQuestion>lions live 10 years</nameQuestion>
                                    <answers>
                                        <answer>10 years</answer>
                                        <answer>2 years</answer>
                                    </answers>
                                </question>

                            </questions>

                        </test>
                    </lesson>
                </lessons>
            </theme>
        </themes>
    </person>
</persons>
