=== JeromeAstero/JD2018-11-13/src/by/it/mnovikov/jd02_08/organization.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://it-academy.by/jd2018-11-13/mnovikov"
        xmlns:mtp="http://it-academy.by/jd2018-11-13/mnovikov"
        elementFormDefault="qualified">
    <element name="organizations">
        <complexType>
            <sequence>
                <element name="organization"
                         type="mtp:Organization"
                         maxOccurs="unbounded"/>
            </sequence>
        </complexType>
    </element>

    <complexType name="Organization">
        <sequence>
            <element name="name" type="string"/>
            <element name="adress" type="string"/>
            <element name="telephone" type="string"/>
            <element name="email" type="string"/>
            <element name="ads"
                     type="mtp:Ads"/>
        </sequence>
    </complexType>

    <complexType name="Ads">
        <sequence>
            <element name="ad"
                     type="mtp:Ad"
                     minOccurs="0"
                     maxOccurs="unbounded"/>
        </sequence>
    </complexType>

    <complexType name="Ad">
        <sequence>
            <element name="title" type="string"/>
            <element name="discription" type="string"/>
            <element name="sampler_type" type="string"/>
            <element name="sampler_title" type="string"/>
            <element name="productivity" type="mtp:Productivity"/>
            <element name="price" type="mtp:Price"/>
        </sequence>
    </complexType>

    <complexType name="Price">
        <simpleContent>
            <extension base="float">
                <attribute name="currency" type="string"/>
            </extension>
        </simpleContent>
    </complexType>
    
    <complexType name="Productivity">
        <simpleContent>
            <extension base="float">
                <attribute name="unit" type="string"/>
            </extension>
        </simpleContent>
    </complexType>

</schema>

=== JeromeAstero/JD2018-11-13/src/by/it/mnovikov/jd02_07/organization+xsd.xml
<?xml version="1.0" encoding="UTF-8" ?>
<organizations xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
               xmlns="http://it-academy.by/jd2018-11-13/mnovikov"
               xsi:schemaLocation="http://it-academy.by/jd2018-11-13/mnovikov organization.xsd">
    <organization>
        <name>SoilQuality</name>
        <adress>Минск, Кнорина, 111</adress>
        <telephone>+375-29-288-12-19</telephone>
        <email>soilquality@mail.ru</email>
        <ads>
            <ad>
                <title>Fast soil sampling</title>
                <discription>Проведение пробоотбора проб почвы с использованием средств механизации</discription>
                <sampler_type>автоматический</sampler_type>
                <sampler_title>Nietfeld Speedprobe</sampler_title>
                <productivity>60</productivity>
                <price>20</price>
            </ad>
            <ad>
                <title>Slow soil sampling</title>
                <discription>Проведение пробоотбора проб почвы без использования средств механизации</discription>
                <sampler_type>ручной</sampler_type>
                <sampler_title>Nietfeld Speedprobe</sampler_title>
                <productivity>10</productivity>
                <price>10</price>
            </ad>
        </ads>
    </organization>
</organizations>
