=== JeromeAstero/JD2018-11-13/src/by/it/zakharenko/jd02_07/clients.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="D:\JD2018-11-13\src\by\it\zakharenko\jd02_07\clients.xml"
        xmlns:tns="D:\JD2018-11-13\src\by\it\zakharenko\jd02_07\clients.xml"
        elementFormDefault="qualified">

    <element name="clients">
        <complexType>
            <sequence>
                <element name="client"
                         type="tns:client"
                         maxOccurs="unbounded"/>
            </sequence>
        </complexType>
    </element>


    <complexType name="client">
        <sequence>
            <element name="e-mail" type="string"/>
            <element name="login" type="string"/>
            <element name="password" type="string"/>
            <element name="phone_number" type="string"/>
            <element name="orders" type="tns:Orders"/>
        </sequence>
    </complexType>

    <complexType name="Orders">
        <sequence>
            <element name="order"
                     type="tns:Order"
                     minOccurs="0"
                     maxOccurs="unbounded"/>
        </sequence>
    </complexType>


    <complexType name="Order">
        <sequence>
            <element name="name" type="string"/>
            <element name="item" type="string"/>
            <element name="item_id" type="string"/>
            <element name="colour" type="string"/>
            <element name="price" type="string"/>
            <element name="address" type="string"/>
        </sequence>
    </complexType>
</schema>

=== JeromeAstero/JD2018-11-13/src/by/it/zakharenko/jd02_07/clients+xsd.xml
<?xml version="1.0" encoding="utf-8"?>

<clients xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="D:\JD2018-11-13\src\by\it\zakharenko\jd02_07\clients.xml clients.xsd"
         xmlns="D:\JD2018-11-13\src\by\it\zakharenko\jd02_07\clients.xml"
>
     <client>
            <e-mail>Lizazakharenko@gmail.com</e-mail>
            <login>lizazakharenko</login>
            <password>12345678</password>
            <phone_number>+375297658895</phone_number>
            <orders>
                <order>
                    <name>Vacuum cleaner</name>
                    <item>Samsung SC5241</item>
                    <item_id>1234</item_id>
                    <colour>grey</colour>
                    <price>129</price>
                    <address>Minsk, Rokossovskogo ave, 145-173</address>
                </order>
                <order>
                    <name>Washing machine</name>
                    <item>LG F2J5HS3W</item>
                    <item_id>1253</item_id>
                    <colour>white</colour>
                    <price>799</price>
                    <address>Minsk, Rokossovskogo ave, 145-173</address>
                </order>
            </orders>
        </client>
    </clients>
