=== JeromeAstero/JD2018-11-13/src/by/it/nickgrudnitsky/jd02_07/twitch.xsd
<?xml version="1.0" encoding="UTF-8" ?>


<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="IT-Academy/JD2018-11-13/src/by/it/nickgrudnitsky"
        xmlns:mtp="IT-Academy/JD2018-11-13/src/by/it/nickgrudnitsky"
        elementFormDefault="qualified">
    <element name="twitch">
        <complexType>
            <sequence>
                <element name="viewers"
                         type="mtp:Viewers"
                         minOccurs="0"
                />
                <element name="streamers"
                         type="mtp:Streamers"
                         minOccurs="0"
                />
            </sequence>
        </complexType>
    </element>

    <complexType name="Viewers">
        <sequence>
            <element name="viewer"
                     type="mtp:Viewer"
                     minOccurs="0"
                     maxOccurs="unbounded"
            />
        </sequence>
    </complexType>

    <complexType name="Viewer">
        <sequence>
            <element name="id" type="long"/>
            <element name="email" type="string"/>
            <element name="password" type="string"/>
            <element name="nickname" type="string"/>
            <element name="following" type="mtp:Following"/>
        </sequence>
    </complexType>

    <complexType name="Following">
        <sequence>
            <element name="channelname"
                     type="string"
                     minOccurs="0"
                     maxOccurs="unbounded"
            />
        </sequence>
    </complexType>

    <complexType name="Streamers">
        <sequence>
            <element name="streamer"
                     type="mtp:Streamer"
                     minOccurs="0"
            />
        </sequence>
    </complexType>

    <complexType name="Streamer">
        <sequence>
            <element name="id" type="long"/>
            <element name="email" type="string"/>
            <element name="password" type="string"/>
            <element name="channelname" type="string"/>
            <element name="followers" type="mtp:Followers"/>
        </sequence>
    </complexType>

    <complexType name="Followers">
        <sequence>
            <element name="nickname"
                     type="string"
                     minOccurs="0"
                     maxOccurs="unbounded"
            />
        </sequence>
    </complexType>
</schema>

=== JeromeAstero/JD2018-11-13/src/by/it/nickgrudnitsky/jd02_07/twitch+xsd.xml
<?xml version="1.0" encoding="UTF-8" ?>



<twitch xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xmlns="IT-Academy/JD2018-11-13/src/by/it/nickgrudnitsky"
        xsi:schemaLocation="http://it-academy.by/jd2018-11-13/nickgrudnitsky twitch.xsd"
>
    <viewers>
        <viewer>
            <email>grudnitsky@gmail.com</email>
            <password>password</password>
            <nickname>NickGS</nickname>
            <following>
                <channelname>Ninja</channelname>
                <channelname>pewdiepie</channelname>
                <channelname>SilverName</channelname>
            </following>
        </viewer>
        <viewer>
            <email>pewdiepie@pewd.se</email>
            <password>youlaughyouloose</password>
            <nickname>pewdiepie</nickname>
            <following>
                <channelname>Ninja</channelname>
            </following>
        </viewer>
    </viewers>

    <streamers>
        <streamer>
            <email>ninja@gmail.com</email>
            <password>fortnightlover</password>
            <channelname>Ninja</channelname>
            <followers>
                <nickname>NickGS</nickname>
                <nickname>pewdiepie</nickname>
            </followers>
        </streamer>
    </streamers>
</twitch>
