=== JeromeAstero/JD2018-11-13/src/by/it/nickgrudnitsky/jd02_07/twitch.dtd
<?xml version="1.0" encoding="utf-8" ?>

        <!ELEMENT twitch (viewers)? (streamers)?>
        <!ELEMENT viewers (viewer)*>
        <!ELEMENT viewer (email, password, nickname, following)>
        <!ELEMENT email (#PCDATA)>
        <!ELEMENT password (#PCDATA)>
        <!ELEMENT nickname (#PCDATA)>
        <!ELEMENT following (channelname?)>
        <!ELEMENT channelname (#PCDATA)>
        <!ELEMENT  streamers (streamer)*>
        <!ELEMENT  streamer (email, password, channelname, followers)>
        <!ELEMENT followers (nickname)*>

=== JeromeAstero/JD2018-11-13/src/by/it/nickgrudnitsky/jd02_07/twitch+dtd.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE twitch SYSTEM "twitch.dtd">
<twitch>
    <viewers>
        <viewer>
            <email>grudnitsky@gmail.com</email>
            <password>password</password>
            <nickname>NickGS</nickname>
            <following>
                <channelname>Ninja</channelname>
                <channelname>pewdiepie</channelname>
                <channelname>SilverName</channelname>
            </following>
        </viewer>
        <viewer>
            <email>pewdiepie@pewd.se</email>
            <password>youlaughyouloose</password>
            <nickname>pewdiepie</nickname>
        </viewer>
    </viewers>

    <streamers>
        <streamer>
            <email>ninja@gmail.com</email>
            <password>fortnightlover</password>
            <channelname>Ninja</channelname>
            <followers>
                <nickname>NickGS</nickname>
                <nickname>pewdiepie</nickname>
            </followers>
        </streamer>
    </streamers>
</twitch>
