=== JeromeAstero/JD2018-11-13/src/by/it/medvedeva/jd02_07/person.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://it-academy.by/jd2018-11-13/akhmelev"
        xmlns:mtp="http://it-academy.by/jd2018-11-13/akhmelev"
        elementFormDefault="qualified">
    <element name="persons">
        <complexType>
            <sequence>
                <element name="person"
                         type="mtp:Person"
                         minOccurs="1" 
                         maxOccurs="unbounded"
                />
            </sequence>
        </complexType>
    </element>
    
    <complexType name="Person">
        <sequence>
            <element name="email" type="string"/>
            <element name="nickname" type="string"/>
            <element name="password" type="string"/>
            <element name="ads" type="mtp:Ads"/>
        </sequence>
    </complexType>
    
    <complexType name="Ads">
        <sequence>
            <element 
                    name="ad" 
                    type="mtp:Ad"
                    minOccurs="0"
                    maxOccurs="unbounded">
            </element>
        </sequence>
    </complexType>
    
    <complexType name="Ad">
        <all>
            <element name="description" type="string"/>
            <element name="address" type="string"/>
            <element name="rooms" type="positiveInteger"/>
            <element name="floor" type="integer"/>
            <element name="floors" type="positiveInteger"/>
            <element name="area" type="float"/>
            <element name="price" type="mtp:Price"/>
        </all>
    </complexType>

    <complexType name="Price">
        <simpleContent>
            <extension base="float">
                <attribute name="currency" type="string"/>
            </extension>
        </simpleContent>
    </complexType>


</schema>

=== JeromeAstero/JD2018-11-13/src/by/it/medvedeva/jd02_07/person+xsd.xml
<?xml version="1.0" encoding="UTF-8" ?>
<persons xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xmlns="http://it-academy.by/jd2018-11-13/akhmelev"
         xsi:schemaLocation="http://it-academy.by/jd2018-11-13/akhmelev person.xsd"
>
    <person>
        <email>vasya@mail.ru</email>
        <nickname>Vasya</nickname>
        <password>Vasya1980</password>
        <ads>
            <ad>
                <description>Шикарный нумер You&amp;I</description>
                <address>Минск Ленина 1 71</address>
                <rooms>3</rooms>
                <floor>3</floor>
                <floors>5</floors>
                <area>55.5</area>
                <price>77777</price>
            </ad>
            <ad>
                <description>Убитый нумер </description>
                <address>Минск Жожская 1 1</address>
                <floor>1</floor>
                <rooms>1</rooms>
                <floors>1</floors>
                <area>25.5</area>
                <price currency="$">37777</price>
            </ad>
        </ads>
    </person>
</persons>
