=== JeromeAstero/JD2018-11-13/src/by/it/zhivov/jd02_07/person.dtd
<?xml version="1.0" encoding="UTF-8"?>
        <!ELEMENT persons (user)+>
        <!ELEMENT user (name,sex,dateOfBirth,email,login,password,tel,ads)>
        <!ELEMENT name (#PCDATA)>
        <!ELEMENT sex (#PCDATA)>
        <!ELEMENT dateOfBirth (#PCDATA)>
        <!ELEMENT email (#PCDATA)>
        <!ELEMENT login (#PCDATA)>
        <!ELEMENT password (#PCDATA)>
        <!ELEMENT tel (#PCDATA)>
        <!ELEMENT ads (ad)*>
<!ELEMENT ad (description,brand,model,color,body,year,equipment,mileage,crashed,price)>
        <!ELEMENT description (#PCDATA)>
        <!ELEMENT brand (#PCDATA)>
        <!ELEMENT model (#PCDATA)>
        <!ELEMENT color (#PCDATA)>
        <!ELEMENT body (#PCDATA)>
        <!ELEMENT year (#PCDATA)>
        <!ELEMENT equipment (#PCDATA)>
        <!ELEMENT mileage (#PCDATA)>
        <!ELEMENT crashed (#PCDATA)>
        <!ELEMENT price (#PCDATA)>

=== JeromeAstero/JD2018-11-13/src/by/it/zhivov/jd02_07/person.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE persons SYSTEM "person.dtd">
<persons>
    <user>
        <name>Живов Антон Дмитриевич</name>
        <sex>Мужской</sex>
        <dateOfBirth>23.12.1994</dateOfBirth>
        <email>jeromeastero@gmai.com</email>
        <login>Jerome</login>
        <password>0123456789</password>
        <tel>+375333830046</tel>
        <ads>
            <ad>
                <description>Лучшее авто за 4000$</description>
                <brand>Toyota</brand>
                <model>Camry</model>
                <color>Grey</color>
                <body>Sedan</body>
                <year>2009</year>
                <equipment>Full lux</equipment>
                <mileage>126000</mileage>
                <crashed>No</crashed>
                <price>4300</price>
            </ad>
            <ad>
                <description>Низкий таз</description>
                <brand>ВАЗ</brand>
                <model>2106</model>
                <color>Murena</color>
                <body>Sedan</body>
                <year>1992</year>
                <equipment>Standart</equipment>
                <mileage>586000</mileage>
                <crashed>Yes</crashed>
                <price>250</price>
            </ad>
            <ad>
                <description>Семейный авто</description>
                <brand>Chrysler</brand>
                <model>Voyager</model>
                <color>Black</color>
                <body>Minivan</body>
                <year>1999</year>
                <equipment>Comfort</equipment>
                <mileage>250000</mileage>
                <crashed>No</crashed>
                <price>5500</price>
            </ad>
        </ads>
    </user>
</persons>
