=== JeromeAstero/JD2018-11-13/src/by/it/skarpovich/jd02_07/buyers.dtd
<?xml version="1.0" encoding="utf-8" ?>
        <!ELEMENT buyers (buyer)+>
        <!ELEMENT buyer (fullname, email, username, password, phone, purchases)>
        <!ELEMENT fullname (#PCDATA)>
        <!ELEMENT email (#PCDATA)>
        <!ELEMENT username (#PCDATA)>
        <!ELEMENT password (#PCDATA)>
        <!ELEMENT phone (#PCDATA)>
<!ELEMENT purchases (purchase)*>
<!ELEMENT purchase (item, item_id, color, price, shipping_address)>
        <!ELEMENT item (#PCDATA)>
        <!ELEMENT item_id (#PCDATA)>
        <!ELEMENT color (#PCDATA)>
        <!ELEMENT price (#PCDATA)>
        <!ELEMENT shipping_address (#PCDATA)>

=== JeromeAstero/JD2018-11-13/src/by/it/skarpovich/jd02_07/buyers+dtd.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE buyers SYSTEM "buyers.dtd">
<buyers>
    <buyer>
        <fullname>John Doe</fullname>
        <email>johndoe@yahoo.com</email>
        <username>john</username>
        <password>john1</password>
        <phone>212-564-5555</phone>
        <purchases>
            <purchase>
                <item>Iphone X 3gb/128gb</item>
                <item_id>1023000</item_id>
                <color>black</color>
                <price>999</price>
                <shipping_address>444 W. 27th Street, 4th Floor, New York, NY 10001</shipping_address>
            </purchase>
            <purchase>
                <item>Xiaomi Redmi Note 5 3gb/32gb</item>
                <item_id>1070099</item_id>
                <color>red</color>
                <price>200</price>
                <shipping_address>555 W. 27th Street, 5rd Floor, New York, NY 10001</shipping_address>
            </purchase>
        </purchases>
    </buyer>
</buyers>
