=== JeromeAstero/JD2018-11-13/src/by/it/naumenko/jd02_07/saleOfCakes.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://it-academy.by/jd2018-11-13/naumenko"
        xmlns:myType="http://it-academy.by/jd2018-11-13/naumenko"
        elementFormDefault="qualified">
    <element name="saleOfCakes">
        <complexType>
            <sequence>
                <element name="sale"
                         type="myType:sale"
                         minOccurs="0"
                         maxOccurs="unbounded"/>
                <element name="tovar"
                         type="myType:tovar"
                         minOccurs="0"
                         maxOccurs="unbounded"/>
                <element name="client"
                         type="myType:client"
                         minOccurs="0"
                         maxOccurs="unbounded"/>
            </sequence>
        </complexType>
    </element>

    <complexType name="sale">
        <sequence>
            <element name="data" type="string"/>
            <element name="email_klient" type="string"/>
            <element name="id_tovara" type="string"/>
            <element name="virychka" type="float"/>
        </sequence>
    </complexType>

    <complexType name="tovar">
        <sequence>
            <element name="cake" type="myType:cake"/>
            <element name="capCakes" type="myType:capCakes"/>
            <element name="gingerbread" type="myType:gingerbread"/>
            <element name="candy" type="myType:candy"/>
            <element name="marshmallow" type="myType:marshmallow"/>
        </sequence>
    </complexType>

    <complexType name="cake">
        <all>
            <element name="name_cake" type="string"/>
            <element name="weight" type="positiveInteger"/>
            <element name="biscuit_cake" type="string"/>
            <element name="filling_cake" type="string"/>
            <element name="cream_cake" type="string"/>
            <element name="decoration_cake" type="string"/>
            <element name="price_cake" type="myType:price_cake"/>
        </all>
    </complexType>

    <complexType name="capCakes">
    <sequence>
        <element name="biscuit_capCakes" type="string"/>
        <element name="cream_cup" type="string"/>
        <element name="filling_cup" type="string"/>
        <element name="decoration_cup" type="string"/>
        <element name="count_cup" type="positiveInteger"/>
        <element name="price_cup" type="float"/>
        <element name="color_cup" type="string"/>
    </sequence>
</complexType>

    <complexType name="gingerbread">
        <sequence>
            <element name="decoration_pr" type="string"/>
            <element name="size_pr" type="positiveInteger"/>
            <element name="count_pr" type="positiveInteger"/>
            <element name="price_pr" type="float"/>
        </sequence>
    </complexType>


    <complexType name="candy">
        <sequence>
            <element name="form_candy" type="string"/>
            <element name="size_canndy" type="positiveInteger"/>
            <element name="caramel_candy" type="string"/>
            <element name="count_candy" type="positiveInteger"/>
            <element name="decoration_candy" type="string"/>
            <element name="price_candy" type="float"/>
        </sequence>
    </complexType>


    <complexType name="marshmallow">
        <sequence>
            <element name="form_z" type="string"/>
            <element name="size_z" type="positiveInteger"/>
            <element name="taste_z" type="string"/>
            <element name="color_z" type="string"/>
            <element name="count_z" type="positiveInteger"/>
            <element name="decoration_Z" type="string"/>
            <element name="price_Z" type="float"/>
        </sequence>
    </complexType>

    <complexType name="client">
        <sequence>
            <element name="lastName" type="string"/>
            <element name="firstName" type="string"/>
            <element name="email" type="string"/>
            <element name="tel" type="string" />
        </sequence>
    </complexType>

    <complexType name="price_cake">
        <simpleContent>
            <extension base="float">
                <attribute name="currensy" type="string"/>
            </extension>
        </simpleContent>

    </complexType>
</schema>

=== JeromeAstero/JD2018-11-13/src/by/it/naumenko/jd02_07/saleOfCakes+xsd.xml
<?xml version="1.0" encoding="utf-8" ?>
<saleOfCakes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
             xmlns="http://it-academy.by/jd2018-11-13/naumenko"
             xsi:schemaLocation="http://it-academy.by/jd2018-11-13/naumenko saleOfCakes.xsd">

    <sale>
        <data>12.01.2019</data>
        <email_klient>Sergey@gmail.com</email_klient>
        <id_tovara>1</id_tovara>
        <virychka>60</virychka>
    </sale>

    <tovar>
        <!--торты-->
        <cake>
            <name_cake>прекрасная краса</name_cake>
            <weight>3</weight>
            <biscuit_cake>красный бархат</biscuit_cake>
            <filling_cake>вишневое конфи</filling_cake>
            <cream_cake>creamChies</cream_cake>
            <decoration_cake>ягоды</decoration_cake>
            <price_cake currensy="руб">25</price_cake>
        </cake>

        <!--капкейки-->
        <capCakes>
            <biscuit_capCakes>красный бархат</biscuit_capCakes>
            <cream_cup>creamChies</cream_cup>
            <filling_cup>вишневое конфи</filling_cup>
            <decoration_cup>ягоды</decoration_cup>
            <count_cup>12</count_cup>
            <price_cup>3</price_cup>
            <color_cup>blue</color_cup>
        </capCakes>

        <!--пряники-->
        <gingerbread>
            <decoration_pr>ягоды</decoration_pr>
            <size_pr>10</size_pr>
            <count_pr>12</count_pr>
            <price_pr>5</price_pr>
            <!--<tecto>красный бархат</tecto>-->
        </gingerbread>

        <!--леденцы-->
        <candy>
            <form_candy>круг</form_candy>
            <size_canndy>5</size_canndy>
            <caramel_candy>малиновая</caramel_candy>
            <count_candy>12</count_candy>
            <decoration_candy>ягоды</decoration_candy>
            <price_candy>5</price_candy>
        </candy>

        <!--зефир и меренги-->
        <marshmallow>
            <form_z>круг</form_z>
            <size_z>7</size_z>
            <taste_z>малиновый</taste_z>
            <color_z>красный</color_z>
            <count_z>12</count_z>
            <decoration_Z>ягоды</decoration_Z>
            <price_Z>0.5</price_Z>
        </marshmallow>

    </tovar>

    <client>
        <lastName>Пупкин</lastName>
        <firstName>Сергей</firstName>
        <email>Sergey@gmail.com</email>
        <tel>8(029)370-19-67</tel>
    </client>

</saleOfCakes>
