=== JeromeAstero/JD2018-11-13/src/by/it/seroglazov/jd02_09/manualXML/recipes.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://generate.jd02_09.seroglazov.it.by/recipes"
        xmlns:mtp="http://generate.jd02_09.seroglazov.it.by/recipes"
        elementFormDefault="qualified">

    <element name="recipes">
        <complexType>
            <sequence>
                <element name="recipe"
                         type="mtp:Recipe"
                         maxOccurs="unbounded"/>
            </sequence>
        </complexType>
    </element>

    <complexType name="Recipe">
        <sequence>
            <element name="cocktail_id" type="ID"/>
            <element name="name" type="string"/>
            <element name="tags" type="mtp:Tag"/>
            <element name="components" type="mtp:Components"/>
            <element name="description" type="string"/>
        </sequence>
    </complexType>

    <complexType name="Tag">
        <sequence>
            <element name="tag" type="string" minOccurs="0" maxOccurs="unbounded"/>
        </sequence>
    </complexType>

    <complexType name="Components">
        <sequence>
            <element name="component" type="mtp:Component" minOccurs="2" maxOccurs="unbounded"/>
        </sequence>
    </complexType>

    <complexType name="Component">
        <sequence>
            <element name="id" type="string"/>
            <element name="amount" type="mtp:Amount"/>
            <element name="unit" type="string"/>
            <element name="garnish" type="boolean"/>
        </sequence>
    </complexType>

    <simpleType name="Amount">
        <restriction base="string">
            <pattern value="[0-9.-]+|few"/>
        </restriction>
    </simpleType>

</schema>

=== JeromeAstero/JD2018-11-13/src/by/it/seroglazov/jd02_09/manualXML/recipes+xsd.xml
<?xml version="1.0" encoding="UTF-8" ?>
<recipes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://generate.jd02_09.seroglazov.it.by/recipes"
         xsi:schemaLocation="http://generate.jd02_09.seroglazov.it.by/recipes recipes.xsd">
    <recipe>
        <cocktail_id>c1</cocktail_id>
        <name>white lady</name>
        <tags>
            <tag>all day cocktail</tag>
        </tags>
        <components>
            <component>
                <id>i100</id>
                <amount>4</amount>
                <unit>cl</unit>
                <garnish>false</garnish>
            </component>
            <component>
                <id>i104</id>
                <amount>3</amount>
                <unit>cl</unit>
                <garnish>false</garnish>
            </component>
            <component>
                <id>i105</id>
                <amount>1</amount>
                <unit>slice</unit>
                <garnish>false</garnish>
            </component>
        </components>
        <description>Add all ingredients into cocktail shaker filled with ice. Shake well and strain into large cocktail glass.</description>
    </recipe>
    <recipe>
        <cocktail_id>c2</cocktail_id>
        <name>old fashioned</name>
        <tags>
            <tag>before dinner cocktail</tag>
        </tags>
        <components>
            <component>
                <id>i106</id>
                <amount>4.5</amount>
                <unit>cl</unit>
                <garnish>false</garnish>
            </component>
            <component>
                <id>i108</id>
                <amount>2</amount>
                <unit>dash</unit>
                <garnish>false</garnish>
            </component>
            <component>
                <id>i109</id>
                <amount>1</amount>
                <unit>cube</unit>
                <garnish>false</garnish>
            </component>
            <component>
                <id>i110</id>
                <amount>few</amount>
                <unit>dash</unit>
                <garnish>false</garnish>
            </component>
            <component>
                <id>i111</id>
                <amount>1</amount>
                <unit>slice</unit>
                <garnish>true</garnish>
            </component>
            <component>
                <id>i112</id>
                <amount>1</amount>
                <unit>piece</unit>
                <garnish>true</garnish>
            </component>
        </components>
        <description>Place sugar cube in old-fashioned glass and saturate with bitters, add a dash of plain water. Muddle until dissolve. Fill the glass with ice cubes and add whiskey. Garnish with orange slice and a cocktail cherry.</description>
    </recipe>
</recipes>
