=== JeromeAstero/JD2018-11-13/src/by/it/markelov/jd02_09/clients.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="schemeToBeans.jd02_09.markelov.it.by"
        xmlns:tns="schemeToBeans.jd02_09.markelov.it.by"
        elementFormDefault="qualified">

    <element name="clients">
        <complexType>
            <sequence>
                <element name="client"
                         type="tns:client"
                         maxOccurs="unbounded"/>
            </sequence>
        </complexType>
    </element>


    <complexType name="client">
        <sequence>
            <element name="e-mail" type="string"/>
            <element name="login" type="string"/>
            <element name="password" type="string"/>
            <element name="orders" type="tns:Orders"/>
        </sequence>
    </complexType>

    <complexType name="Orders">
        <sequence>
            <element name="order"
                     type="tns:Order"
                     minOccurs="0"
                     maxOccurs="unbounded"/>
        </sequence>
    </complexType>


    <complexType name="Order">
        <sequence>
            <element name="name" type="string"/>
            <element name="code" type="string"/>
            <element name="size" type="string"/>
            <element name="colour" type="string"/>
            <element name="delivery_address" type="string"/>
            <element name="phone_number" type="string"/>
        </sequence>
    </complexType>
</schema>

=== JeromeAstero/JD2018-11-13/src/by/it/markelov/jd02_07/clients+xsd.xml
<?xml version="1.0" encoding="utf-8"?>

<clients xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="D:\JD2018-11-13\src\by\it\markelov\jd02_07\clients.xml clients.xsd"
xmlns="D:\JD2018-11-13\src\by\it\markelov\jd02_07\clients.xml">
    <client>
        <e-mail>S_markelov@tut.by</e-mail>
        <login>S_markelov</login>
        <password>12345678</password>
        <orders>
            <order>
                <name>sneakers</name>
                <code>20681</code>
                <size>42</size>
                <colour>green</colour>
                <delivery_address>Minsk, Belskogo, 27-79</delivery_address>
                <phone_number>(29)715-97-50</phone_number>
            </order>
            <order>
                <name>shoes</name>
                <code>14205</code>
                <size>42</size>
                <colour>brown</colour>
                <delivery_address>Minsk, Belskogo, 27-79</delivery_address>
                <phone_number>(29)715-97-50</phone_number>
            </order>
        </orders>
    </client>
</clients>
