=== JeromeAstero/JD2018-11-13/src/by/it/seroglazov/jd02_07/ingredients/ingredients.dtd
<?xml version="1.0" encoding="UTF-8" ?>
<!ELEMENT ingredients (ingredient)+>
<!ELEMENT ingredient (name, tags*)>
<!ATTLIST ingredient id ID #REQUIRED>
<!ELEMENT name (#PCDATA)>
<!ELEMENT tags (tag)*>
<!ELEMENT tag (#PCDATA)>

=== JeromeAstero/JD2018-11-13/src/by/it/seroglazov/jd02_07/ingredients/ingredients+dtd.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE ingredients SYSTEM "ingredients.dtd">
<ingredients>
    <ingredient id="i100">
        <name>gin</name>
        <tags>
            <tag>alcoholic beverage</tag>
        </tags>
    </ingredient>
    <ingredient id="i101">
        <name>freshly squeezed lemon juice</name>
        <tags>
            <tag>juice</tag>
            <tag>citrus</tag>
        </tags>
    </ingredient>
    <ingredient id="i102">
        <name>cointreau</name>
        <tags>
            <tag>alcoholic beverage</tag>
            <tag>liqueur</tag>
        </tags>
    </ingredient>
    <ingredient id="i104">
        <name>triple sec</name>
        <tags>
            <tag>alcoholic beverage</tag>
            <tag>liqueur</tag>
        </tags>
    </ingredient>
    <ingredient id="i105">
        <name>lemon</name>
        <tags>
            <tag>citrus</tag>
        </tags>
    </ingredient>
    <ingredient id="i106">
        <name>bourbon whiskey</name>
        <tags>
            <tag>alcoholic beverage</tag>
            <tag>whisky</tag>
        </tags>
    </ingredient>
    <ingredient id="i107">
        <name>scotch whisky</name>
        <tags>
            <tag>alcoholic beverage</tag>
            <tag>whisky</tag>
        </tags>
    </ingredient>
    <ingredient id="i108">
        <name>angostura aromatic bitters</name>
        <tags>
            <tag>alcoholic beverage</tag>
            <tag>bitter</tag>
        </tags>
    </ingredient>
    <ingredient id="i109">
        <name>sugar</name>
    </ingredient>
    <ingredient id="i110">
        <name>plain water</name>
        <tags>
            <tag>non-alcoholic beverage</tag>
        </tags>
    </ingredient>
    <ingredient id="i111">
        <name>orange</name>
        <tags>
            <tag>citrus</tag>
        </tags>
    </ingredient>
    <ingredient id="i112">
        <name>cocktail cherry</name>
    </ingredient>
</ingredients>
