=== JeromeAstero/JD2018-11-13/src/by/it/denisova/jd02_09/english.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://it-academy.by/jd2018-11-13/denisova"
        xmlns:mtp="http://it-academy.by/jd2018-11-13/denisova"
        elementFormDefault="qualified">

    <element name="persons">
        <complexType>
            <sequence>
                <element name="person"
                         type="mtp:Person"
                         minOccurs="1"
                         maxOccurs="unbounded"
                />
            </sequence>
        </complexType>
    </element>

    <complexType name="Person">
        <sequence>
            <element name="email" type="string"/>
            <element name="nickname" type="string"/>
            <element name="password" type="string"/>
            <element name="themes" type="mtp:Themes"/>

        </sequence>
    </complexType>


    <complexType name="Themes">
        <all>
            <element name="theme" type="mtp:Theme"
                     minOccurs="1"
                     />
        </all>
    </complexType>


    <complexType name="Theme">
        <sequence>
            <element name="name" type="string"/>
            <element name="lessons" type="mtp:Lessons"/>
        </sequence>
    </complexType>


    <complexType name="Lessons">
        <sequence>
            <element name="lesson" type="mtp:Lesson"/>
        </sequence>
    </complexType>

    <complexType name="Lesson">
        <all>
            <element name="name" type="string"
                     minOccurs="0"
                     />
            <element name="level" type="string" />
            <element name="theory" type="string"></element>
            <element name="test" type="mtp:Test"></element>

        </all>
    </complexType>

        <complexType name="Test">
            <all>
                <element name="name" type="string"/>
                <element name="questions" type="mtp:Questions"/>

            </all>
        </complexType>

    <complexType name="Questions">
        <sequence>
            <element name="question" type="mtp:Question"/>
        </sequence>
    </complexType>

    <complexType name="Question">
        <all>
            <element name="name" type="string"/>
            <element name="answers" type="mtp:Answers"/>
        </all>
    </complexType>

    <complexType name="Answers">
        <all>
            <element name="answer" type="string"/>
        </all>
    </complexType>

</schema>

=== JeromeAstero/JD2018-11-13/src/by/it/denisova/jd02_07/english+xsd.xml
<?xml version="1.0" encoding="UTF-8" ?>
<persons xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://it-academy.by/jd2018-11-13/denisova"
         xsi:schemaLocation="http://it-academy.by/jd2018-11-13/denisova english.xsd"
>
    <person>
        <email></email>
        <nickname></nickname>
        <password></password>
        <themes>
            <theme>
                <name>Animals</name>
                <lessons>
                    <lesson>
                        <name>Animals read</name>
                        <level>Easy</level>
                        <theory> (some theory) example: leon lives 10 years</theory>
                        <test>
                            <name>first</name>
                            <questions>
                                <question>
                                    <name>how many lives lion?</name>
                                    <answers>
                                        <answer>10 years</answer>
                                    </answers>
                                </question>
                            </questions>
                        </test>
                    </lesson>
                </lessons>
            </theme>
        </themes>
    </person>
</persons>
